### ISSUE TITLE
Certificate extension error while running sample client-server code

### ISSUE THREAD

**Issue by graziadonghia** [inclavare-containers/rats-tls#112]
Hello, I'm trying to run the sample rats-TLS code with client (`./rats-tls-client --attester sgx_ecdsa --tls openssl --crypto openssl -D`) and server (`./rats-tls-server --attester sgx_ecdsa --tls openssl --crypto openssl -D`) but I keep receiving this error:
SERVER
```
    - Welcome to RATS-TLS sample server program for Intel SGX
[INFO] load_enclave()@L47: Success to load enclave with enclave id 2
[INFO] rtls_crypto_wrapper_select()@L67: the crypto wrapper 'openssl' selected
[INFO] rtls_attester_select()@L75: the enclave attester 'sgx_ecdsa' selected
[INFO] rtls_verifier_select()@L75: the enclave verifier 'nullverifier' selected
[INFO] rtls_tls_wrapper_select()@L68: the tls wrapper 'openssl' selected
[load_pce ../pce_wrapper.cpp:179] Call sgx_create_enclave for PCE. /lib/x86_64-linux-gnu/libsgx_pce.signed.so.1
[INFO] ecall_rtls_server_startup()@L91: Waiting for a connection ...
[ERROR] ecall_rtls_server_startup()@L102: Failed to negotiate 0x907fffff
[ERROR] rats_tls_server_startup()@L124: failed to startup enclave server: sgx status 0, ecall return -1
```

CLIENT
```
    - Welcome to RATS-TLS sample client program for Intel SGX
[INFO] load_enclave()@L49: Success to load enclave with enclave id 2
[INFO] rtls_crypto_wrapper_select()@L67: the crypto wrapper 'openssl' selected
[INFO] rtls_attester_select()@L75: the enclave attester 'sgx_ecdsa' selected
[INFO] rtls_verifier_select()@L75: the enclave verifier 'nullverifier' selected
[INFO] rtls_tls_wrapper_select()@L68: the tls wrapper 'openssl' selected
[WARN] tls_wrapper_verify_certificate_extension()@L29: type doesn't match between verifier 'nullverifier' and evidence 'sgx_ecdsa'
[ERROR] rtls_verifier_select()@L64: failed to select the enclave verifier 'sgx_ecdsa'
[ERROR] tls_wrapper_verify_certificate_extension()@L35: the verifier selecting err 0xfffffffe during verifying cert extension
[ERROR] verify_certificate()@L407: failed to verify certificate extension 0x40000000
[ERROR] ecall_rtls_client_startup()@L199: Failed to negotiate 0x907fffff
[ERROR] rats_tls_client_startup()@L77: failed to startup client: sgx status 0 return 0xffffffff
```
What does it mean `failed to verify certificate extension 0x40000000`? What should I do?
Another thing: is it possible to test remote attestation on the same machine? Because I was wondering that maybe it doesn't work because I need two different nodes to perform remote attestation

**Comment by jiazhang0** [comment]
Attester and Verifier are the concepts in RATS architecture. Client and Server are the concepts in network model. Therefore, a client may be either attester or verifier, and a server may be either attester or verifier as well.  In your test, the client acts as attester (because you specify it in `./rats-tls-client --attester sgx_ecdsa --tls openssl --crypto openssl -D`), which implies that the server should act as verifier not attester again. So the correct cmdline for server should be `./rats-tls-server --verifier sgx_ecdsa --tls openssl --crypto openssl -D`.

**Comment by jiazhang0** [comment]
Closed. If you have any question, please reopen this issue.
