### ISSUE TITLE
Failed to build with latest commit a3a3bfc8b33d38eb45bf65dbd05a1472232d6824

### ISSUE THREAD

**Issue by arronwy** [inclavare-containers/rats-tls#143]
Build environment docker image: runetest/compilation-testing:ubuntu18.04:
https://github.com/confidential-containers/ocicrypt-rs/blob/main/.github/workflows/ci.yml#L19

Works with previous commit: 8fbfdb6a99b866c408cbd7ddf40ee744e1dbea55
Build error:
```
[ 63%] Building C object src/verifiers/sgx-ecdsa/CMakeFiles/verifier_sgx_ecdsa.dir/verify_evidence.c.o
/__w/ocicrypt-rs/ocicrypt-rs/rats-tls/src/verifiers/sgx-ecdsa/verify_evidence.c: In function 'ecdsa_verify_evidence':
/__w/ocicrypt-rs/ocicrypt-rs/rats-tls/src/verifiers/sgx-ecdsa/verify_evidence.c:68:5: error: 'sgx_ql_qve_collateral_t {aka struct _sgx_ql_qve_collateral_t}' has no member named 'tee_type'
    .tee_type = 0x00000000, /* SGX */
     ^~~~~~~~
make[2]: *** [src/verifiers/sgx-ecdsa/CMakeFiles/verifier_sgx_ecdsa.dir/verify_evidence.c.o] Error 1
src/verifiers/sgx-ecdsa/CMakeFiles/verifier_sgx_ecdsa.dir/build.make:158: recipe for target 'src/verifiers/sgx-ecdsa/CMakeFiles/verifier_sgx_ecdsa.dir/verify_evidence.c.o' failed
```

**Comment by KB5201314** [comment]
@arronwy We have increased the supported [minimum DCAP version](https://github.com/inclavare-containers/rats-tls/blob/a3a3bfc8b33d38eb45bf65dbd05a1472232d6824/README.md?plain=1#L14-L17) to 1.15. You can use the updated image `runetest/compilation-testing:ubuntu20.04` to fix this. :)

**Comment by arronwy** [comment]
> @arronwy We have increased the [supported minimum SGX DCAP version](https://github.com/inclavare-containers/rats-tls/blob/a3a3bfc8b33d38eb45bf65dbd05a1472232d6824/README.md?plain=1#L14-L17) to 1.15. You can use the updated image `runetest/compilation-testing:ubuntu20.04` to fix this. :)

Thanks for clarification, @KB5201314 , we'll have a try :-)
