### ISSUE TITLE
the verify_ceritificate will be called twice.

### ISSUE THREAD

**Issue by zhiminghufighting** [inclavare-containers/rats-tls#44]
Have no clue to the issue.

**Comment by haosanzi** [comment]
This issue still exists. 

![image](https://user-images.githubusercontent.com/26923638/205838808-5c040cb8-0a53-49a9-bfa3-070fce563381.png)

In rats-tls host mode. After starting the `rats-tls-server`, and then run the `rats-tls-client`, we can see that the callback function is set on line 42. When the client performs function on line 76, the callback function `verify_ceritificate` will be called twice.

**Comment by KB5201314** [comment]
The first call is caused by `preverify_ok=0` and `err=X509_V_ERR_DEPTH_ZERO_SELF_SIGNED_CERT`.

The second call with `preverify_ok=1` is because of the following bolded content.

> The certificate chain is checked starting with the deepest nesting level (the root CA certificate) and worked upward to the peer's certificate. At each level signatures and issuer attributes are checked. Whenever a verification error is found, the error number is stored in x509_ctx and verify_callback is called with preverify_ok=0. By applying X509_CTX_store_* functions verify_callback can locate the certificate in question and perform additional steps (see EXAMPLES). **\*\*If no error is found for a certificate, verify_callback is called with preverify_ok=1 before advancing to the next level.\*\***

https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_verify.html
