### ISSUE TITLE
specify whether to use the ras or ecc algorithm

### ISSUE THREAD

**Issue by zhiminghufighting** [inclavare-containers/rats-tls#49]
How do users specify whether to use the ras or ecc algorithm?
Please add relevant information to the readme.

Now it is the default setting defined in code
typedef enum {
ENCLAVE_TLS_CERT_ALGO_RSA_3072_SHA256,
ENCLAVE_TLS_CERT_ALGO_ECC_256_SHA256,
ENCLAVE_TLS_CERT_ALGO_MAX,
ENCLAVE_TLS_CERT_ALGO_DEFAULT = ENCLAVE_TLS_CERT_ALGO_ECC_256_SHA256
} enclave_tls_cert_algo_t;
can be configured through configure file in future

Sound good. Please open an issue to address this issue.

**Comment by YangLiang3** [comment]
Done
